cad: []
description: This Mod is a simple "One Piece" mount for the popular Electreeks Camera.
discord_username: Backenfutter
images:
- Pictures/Picture1.jpeg
mod_version: 1
printer_compatibility:
- V2.4
title: Mount for Electreeks Camera
