cad:
- CAD/Tophat-with-Extractor.step
description: Tophat Extractor for the Voron V0.1 with activated charcoal and HEPA
  filter
images:
- img/drawing1.png
- img/drawing3.png
- img/drawing2.png
mod_version: 1
printer_compatibility:
- V0
title: V0.1 Tophat Extractor
