cad:
- duet_wifi_mount.step
description: Duet wifi mount in pocketwatch location
discord_username: Nomsplease
images:
- Images/back_compartment.jpg
- Images/closed_back.jpg
mod_version: 1
printer_compatibility:
- V0
title: Duet Wifi Mount
