cad:
- CAD/VoronBlankingBackPlate-v15.f3d
description: Back blanking plate that can be used instead of the exhaust filter housing
  if you are using something like a nevermore filter instead.
images:
- Images/Inside.jpg
- Images/Outside.jpg
- Images/CAD1.png
- Images/CAD2.png
mod_version: 1
printer_compatibility:
- V2.4
title: Back blanking plate
