cad: []
description: Swiveling case for the Fysetc Mini12864 LCD
images:
- Images/LCD_SwivelDown.jpg
- Images/LCD_BackCover.jpg
- Images/LCD_SwivelUp.jpg
- Images/LCD_Detailed.jpg
- Images/LCD_CAD.png
mod_version: 1
printer_compatibility:
- V2.4
title: Mini12864 LCD Mount
