cad: []
description: Simple and slim handles for the V0
discord_username: Ch4rlesB
images:
- Screenshot1.png
- Screenshot2.png
- Screenshot3.png
mod_version: 1
printer_compatibility:
- V0
title: V0 Handles Slim
