cad: []
description: A mount for the BTT PITFT50 v2 Touch Display
discord_username: alanho
images:
- images/f360.jpg
- images/IMG_6451.jpg
- images/IMG_6447.jpg
mod_version: 1
printer_compatibility:
- V2.4
title: BTT PITFT50 v2 Mount
