cad: []
description: v2.4 magnetic clips to retain bottom panel
discord_username: hernsl
images:
- bottom_panel_maghold_panel.jpg
- bottom_panel_maghold_skirt.jpg
- bottom_panel_maghold.jpg
mod_version: 1
printer_compatibility:
- V2.4
title: Bottom Panel Mag Clip
