---
title: "Huvud Chain Mount"
description: "Huvud rear mount for Clockwork or LGX that supports a cable chain."
printer_compatibility:
  - V1.8
  - VT
images:
  - images/huvud_chain_mount.png
  - images/huvud_mount_install1.png
  - images/huvud_mount_install2.png
cad:
  - STEP/huvud_chain_mount_2_hole.step
  - STEP/huvud_chain_mount_3_hole.step
mod_version: 2
