cad:
- CAD/Filament_Runout_Housing.f3d
description: Filament runout sensor that replaces the stock bowden retainer
discord_username: bobbleheed
images:
- IMAGES/Switch_Cross_Section.png
- IMAGES/Internal_Assembly.png
- IMAGES/Assembled.png
mod_version: 1
printer_compatibility:
- V1.8
- V2.4
- Trident
title: Filament Runout Sensor
