cad: []
description: Mount V0 panels with magnets, removes need for hinges and lets you easily
  detach sides for access
discord_username: Yeri
images: []
mod_version: 1
printer_compatibility:
- V0
title: V0 Magnetic Panels
