cad: []
description: V0 Belts Holder
discord_username: TheSquiffy
images:
- Images/bh10.jpg
- Images/bh1.png
- Images/bh3.png
- Images/bh2.png
- Images/bh6.png
- Images/bh7.jpg
- Images/bh5.png
- Images/bh4.png
- Images/bh9.jpg
- Images/bh8.jpg
mod_version: 1
printer_compatibility:
- V0
title: V0 Belts holder
