cad:
- CAD/Voron_KlickyProbe_v2_v56.step
description: Microswitch based inductive probe replacement
discord_username: JosAr
images:
- Printers/v0/Photos/klicky_v0.jpg
- Printers/v0/Photos/V0_dock.jpg
- Printers/v0/Photos/V0.1_probe_mount_3.jpg
- Printers/v0/Photos/probe_wires_detail.png
- Printers/v0/Photos/V0.1_probe_mount_2.jpg
- Printers/v0/Photos/DockMount_fixed.jpg
- Printers/v0/Photos/integrated_mount.jpg
- Printers/v0/Photos/V0.1_probe_mount_1.jpg
- Printers/v0/Photos/V0_probedock_mount.jpg
- Printers/v0/Photos/integrated_cowling_wklicky.jpg
- Printers/v0/Photos/V0.1_complete.jpg
- Printers/v0/Photos/front_cowling_mount.jpg
- Printers/v0/Photos/front_cowling_mount_back.jpg
- Printers/v0/Photos/DockMount_TopScrews.jpg
- Printers/v0/Photos/dockmount_attached.jpg
- Printers/v0/Photos/Fan_duct_v0_mounted.jpg
- Printers/v0/Photos/V0_probe_3.jpg
- Printers/v0/Photos/V0_probe_2.jpg
- Printers/v0/Photos/V0_probe_1.jpg
- Printers/v0/Photos/V0_probe_5.jpg
- Printers/v0/Photos/V0.1_umbilical.jpg
- Printers/v0/Photos/Klicky_v0_family.jpg
- Printers/v0/Photos/V0_probe_4.jpg
- Printers/v0/Photos/DockMount_SideScrews.jpg
- Printers/v0/Photos/V0.1_back.jpg
- Printers/v0/Photos/DockMount_extrabeef.jpg
- Printers/v0/Photos/V0.1_attached.jpg
- Printers/v0/Photos/V0.1_front_cowling_mount.jpg
- Printers/v0/Photos/V0_dock_mount.png
- Printers/v0/Photos/V0_dock_mount.jpg
- Printers/v0/Photos/Fan_duct_v0_wklicky.jpg
- Printers/v0/Photos/DockMount_variable.jpg
- Printers/v1.8_v2.4_Legacy_Trident/Photos/AB_Mount_wiring_1.jpg
- Printers/v1.8_v2.4_Legacy_Trident/Photos/Probe_topside.jpg
- Printers/v1.8_v2.4_Legacy_Trident/Photos/Fixed_sidemount_left.jpg
- Printers/v1.8_v2.4_Legacy_Trident/Photos/AB_Mount_wiring_3.jpg
- Printers/v1.8_v2.4_Legacy_Trident/Photos/AB_Mount_wiring_2.jpg
- Printers/v1.8_v2.4_Legacy_Trident/Photos/DockMount.jpg
- Printers/v1.8_v2.4_Legacy_Trident/Photos/Klicky_probe_press_Helper.jpg
- Printers/v1.8_v2.4_Legacy_Trident/Photos/AB_mount_press_Helper.jpg
- Printers/v1.8_v2.4_Legacy_Trident/Photos/AB_Mount_wiring_4.jpg
- Printers/v1.8_v2.4_Legacy_Trident/Photos/legacy_fixedmount.jpg
- Printers/v1.8_v2.4_Legacy_Trident/Photos/AB_Mount_wiring_complete.jpg
- Printers/v1.8_v2.4_Legacy_Trident/Photos/Klicky_Probe.png
- Printers/v1.8_v2.4_Legacy_Trident/Photos/Klicky_Probe_recommended_printing_orientation.png
- Printers/v1.8_v2.4_Legacy_Trident/Photos/Gantry_Sidemount_installed.jpg
- Printers/v1.8_v2.4_Legacy_Trident/Photos/probe_v1_underside_marked_magnets.jpg
- Printers/v1.8_v2.4_Legacy_Trident/Photos/AB_mount_press_Helper_inuseBack.jpg
- Printers/v1.8_v2.4_Legacy_Trident/Photos/klicky_v1.8_v2.4_Legacy_Trident.jpg
- Printers/v1.8_v2.4_Legacy_Trident/Photos/Klicky_Probe installed.png
- Printers/v1.8_v2.4_Legacy_Trident/Photos/Probe_MStoArrow_alignment.jpg
- Printers/v1.8_v2.4_Legacy_Trident/Photos/AB_mount_press_Helper_inuseTop.jpg
- Printers/v1.8_v2.4_Legacy_Trident/Photos/probe_dock_complete.jpg
- Printers/v1.8_v2.4_Legacy_Trident/Photos/Klicky_probe_press_Helper_inuse.jpg
- Printers/v1.8_v2.4_Legacy_Trident/Photos/Voron_V2.4_300mm_back.jpg
- Printers/v1.8_v2.4_Legacy_Trident/Photos/probe_dock_components.jpg
- Printers/v1.8_v2.4_Legacy_Trident/Photos/Fixed_sidemount_right.jpg
- Printers/v1.8_v2.4_Legacy_Trident/Photos/probe_components.jpg
- Printers/v1.8_v2.4_Legacy_Trident/Photos/probe_v1_underside.jpg
- Printers/v1.8_v2.4_Legacy_Trident/Photos/probe_dock_2.jpg
- Printers/v1.8_v2.4_Legacy_Trident/Photos/Voron_Klicky_Probe.jpg
- Printers/v1.8_v2.4_Legacy_Trident/Photos/probe_install.jpg
- Printers/v1.8_v2.4_Legacy_Trident/Photos/Fixed_mount_complete.jpg
- Printers/v1.8_v2.4_Legacy_Trident/Photos/probe_complete.jpg
- Printers/v1.8_v2.4_Legacy_Trident/Photos/Variable_mount_complete.jpg
- Printers/v1.8_v2.4_Legacy_Trident/Photos/DockMountandProbeMount.jpg
- Printers/v1.8_v2.4_Legacy_Trident/Photos/ABMountInstalled.jpg
- Printers/v1.8_v2.4_Legacy_Trident/Photos/probe_dock_1.jpg
- Printers/v1.8_v2.4_Legacy_Trident/Photos/ABMountCheckforContiuity.jpg
- Photos/Klicky_Probe.png
- Photos/Klicky_Probe_recommended_printing_orientation.png
- Photos/Voron_V2.4_300mm_back.jpg
- Photos/klicky_base.jpg
mod_version: 1
printer_compatibility:
- V0
- V1.8
- V2.4
- Trident
title: Klicky Probe
