cad:
- CAD/top_corner_cable_cover_with_drop_holes_LDO_PCB_splitter_left_rev01.f3d
- CAD/LDO_LED_PCB_spacer_narrow_rev01.f3d
- CAD/top_corner_cable_cover_with_drop_holes_LDO_PCB_splitter_left_rev01.step
- CAD/top_corner_cable_cover_with_drop_holes_LDO_PCB_splitter_right_rev01.step
- CAD/LDO_LED_PCB_spacer_narrow_rev01.step
- CAD/top_corner_cable_cover_with_drop_holes_rev02.step
- CAD/top_corner_cable_cover_with_drop_holes_rev02.f3d
- CAD/top_corner_cable_cover_with_drop_holes_LDO_PCB_splitter_right_rev01.f3d
description: Corner cable cover around Z-idler with drop holes near z frame and cutouts
  for inline wiring from 2020 extrustions
images: []
mod_version: 1
printer_compatibility:
- V2.4
title: Corner Cable Cover with Drop Holes
