---
title: "Side entry exhaust housing"
description: "Exhaust housing with dual cover screws and single or dual side entry filament paths."
printer_compatibility:
  - V2.4
  - V1.8
  - VT
images:
  - images/side_housing_view1.png
  - images/side_housing_view2.png
cad:
  - CAD/exhaust_housing_side_entry.f3d
mod_version: 1
