cad:
- CAD/Filter Cage.step
- CAD/Fan Mounting.step
- CAD/HEPA_Filter.step
description: "Filter case with fan\xB4s"
discord_username: JNP
images:
- Images/1.jpg
mod_version: 1
printer_compatibility:
- V0
title: Hepa Filter
