---
# title: LOL I'm missing
description: "This mod does awesome things with awesome printers!"
printer_compatibility:
  - V0
  - V1
  - V2
  - VSW
  - Trident
  - Ratrig
images:
  - images/huvud_chain_mount.png
  - images/huvud_mount_install1.png
  - images/huvud_mount_install2.png
  - 1
cad:
  - STEP/huvud_chain_mount_2_hole.step
  - STEP/huvud_chain_mount_3_hole.step
discord_username: haribrother
extra_param: LOL I don't belong here!