cad:
- Parametric Filtered Power v1.8.f3d
description: V1.6 Filtered Inlet and Rocker Switch for V1.8
images:
- pictures/Back.png
- pictures/Front.png
mod_version: 1
printer_compatibility:
- V1.8
title: V1.8 Filtered Power Inlet
