cad:
- CAD/Front_Bed_Mount.f3d
description: Printed bed front for kirigami folded metal bed mount with Voron logo.
discord_username: Kosh42EFG
images: []
mod_version: 1
printer_compatibility:
- V0
title: Kirigami bed front
