cad:
- CAD/Quickdraw_for_VSW.step
description: Detachable magnetic probe with docking system for VSW
images:
- Pictures/quickdraw_SW_remix.png
- Pictures/quickdraw_SW_probe.png
- Pictures/SW_Y_travel.png
mod_version: 1
printer_compatibility:
- VSW
title: Quickdraw probe Voron Switchwire
