cad:
- cad/2020-Wago_221-412_tray-5x2.step
description: Smaller 5 port Wago mount that fits parallel to the support rails
discord_username: Boingomw
images:
- images/5x2_front_view.png
- images/5x2_back_view.png
- images/Installed_Older_Version.jpg
mod_version: 1
printer_compatibility:
- V2.4
title: Wago mount
