cad: []
description: A simple safety guard for the terminals on a Crydom GN SSR
images:
- Images/guard.png
- Images/installed.jpg
- CAD/lightning.svg
mod_version: 1
printer_compatibility:
- V2.4
title: Crydom GN Terminal Guard
