cad:
- STM32_Klipper_Expander_v5.step
- STM32_Klipper_Expander_No_Holes_v2.step
description: Mounting brackets for the klipper expander using vhb tape or mounting
  screws
images:
- Images/Mount_Top.jpg
- Images/Mount_Side.jpg
mod_version: 1
printer_compatibility:
- V0.2
- V1.8
- V2.4
- VSW
- VT
title: Klipper Expander Mount
