cad: []
description: 'Clips to help support lower deck panels to prevent (or fix) warping:'
images:
- deck_clip_top.png
- deck_clip_bottom.png
- deck_clip_adjustable.png
- deck_clip_side.png
mod_version: 1
printer_compatibility:
- V1.8
- V2.4
title: Deck Panel Support Clips
