cad:
- CAD/Tophead_Mod_V0_v4.f3d
description: A mount for 10mm LED strips and Exhaust for Voron V0
discord_username: See1807
images:
- img/Foto_2.jpg
- img/Foto_1.jpg
mod_version: 1
printer_compatibility:
- V0
title: TopHat Exhaust and LED Light
