cad:
- 60mm_Shaft_Jig_v2.step
description: Simple jig for cutting and grinding 60mm Z shafts
discord_username: Nomsplease
images: []
mod_version: 1
printer_compatibility:
- V2.4
title: 60mm Shaft Jig
