cad:
- CAD/MiniAB_ADXL_Mount.f3d
description: Mount for an AXDL345 on the Mini Afterburner
images:
- Images/CAD_1.png
- Images/CAD_3.png
- Images/CAD_2.png
- Images/PIC_1.png
mod_version: 1
printer_compatibility:
- V0.2
title: Mini Afterburner ADXL345 Mount
