cad: []
description: Spool holder that mounts on top for "too close to the wall" printers
discord_username: elcrni
images:
- Images/4.png
- Images/5.png
- Images/6.png
- Images/2.png
- Images/3.png
- Images/1.png
mod_version: 1
printer_compatibility:
- V1.8
- V2.4
- Trident
title: V.24/Trident Spool Holder
