cad: []
description: This toolhead uses the stock M2.5 screw that came with the dragon hotend
discord_username: Nashuar
images: []
mod_version: 1
printer_compatibility:
- V0
title: V0 Dragon Toolhead M2.5x8
