cad:
- cad/v0_3x3_wago v2.f3d
- cad/v0_3x3_wago v2.step
description: Easy to install Wago mounts for v0 mains
discord_username: deepfriedheroin
images:
- images/mains_wago_v0_2.jpeg
- images/mains_wago_v0_3.png
- images/mains_wago_v0_1.jpeg
mod_version: 1
printer_compatibility:
- V0
title: v0 Power Wagos
