cad:
- CAD/Trident_Revo_Nozzle_Skirt.step
description: A Revo nozzle box hidden in a Trident skirt.
discord_username: Andre
images:
- Images/Photo-Closed.jpg
- Images/Photo-Opened.jpg
mod_version: 1
printer_compatibility:
- null
title: Revo Nozzle Skirt
