cad:
- STEP/V01-LED-Tophat.step
description: V0.1 LED Tophat w/ 24V LED Lightstrip
discord_username: Shteeeeeve
images:
- Images/V0-LED-Tophat-Photo.jpg
- Images/V01-LED-Tophat-03.jpg
- Images/V01-LED-Tophat-02.jpg
- Images/V01-LED-Tophat-01.jpg
- Images/V01-LED-Tophat-wireframe-1.jpg
mod_version: 1
printer_compatibility:
- V0
title: V0.1 LED Tophat
