cad: []
description: Connector cover for 42STH20-1004AS
discord_username: hhammarstrand
images:
- exodius_afterburner.jpg
- compare.png
mod_version: 1
printer_compatibility:
- VSW
title: Afterburner connector cover for 42STH20-1004AS
