cad: []
description: Mount Adafruit PCB NeoPixel Sticks on the V0 Y-rail extrusions
images:
- images/design.jpg
- images/installed.jpg
- images/wired.jpg
mod_version: 1
printer_compatibility:
- V0.2
title: V0 Adafruit NeoPixel LED Mounts
