cad:
- CAD/Panel right.step
- CAD/Panel left.step
description: Panels with intergrated hinge
discord_username: JNP
images:
- Images/4.jpg
- Images/5.jpg
- Images/2.jpg
- Images/3.jpg
- Images/1.jpg
mod_version: 1
printer_compatibility:
- V0
title: Side Panels
