cad: []
description: Minimalistic backplate for cooler motors and electronics
discord_username: Khay
images:
- img/DSC_2959.jpg
- img/Slicer_pic.png
- img/CAD_pic.jpg
mod_version: 1
printer_compatibility:
- V0
title: V0 Micro Backplate
