cad:
- cad/cable_routing_z_belt_cover_a_mod.step
- cad/cable_routing_z_belt_cover_b_mod.step
description: Z belt covers that allow hidden cable routing.
discord_username: Akio
images:
- img/cable_routing_z_belt_cover_mod_img_0.png
- img/cable_routing_z_belt_cover_mod_img_1.png
- img/cable_routing_z_belt_cover_mod_img_3.jpg
- img/cable_routing_z_belt_cover_mod_img_2.jpg
mod_version: 1
printer_compatibility:
- V2.4
title: Hidden cable routing z belt cover
