cad: []
description: Kirigami bed front with space for a single LED or Neopixel button
images:
- Beddefuser2.jpg
- Bedfront.jpg
mod_version: 1
printer_compatibility:
- V0.2
title: Kirigami LED Bed Front
