cad: []
description: Voron 0.1 Power inlet with keystone insert slot
discord_username: Polared
images:
- images/installed.jpg
mod_version: 1
printer_compatibility:
- V0
title: Power Inlet with Keystone Insert
