cad: []
description: Add a ON/OFF Switch to side or front skirts
discord_username: tayto-chip
images:
- images/IMG_1222.jpeg
- images/IMG_1224.jpeg
mod_version: 1
printer_compatibility:
- V2.4
title: V2.4 Skirt Switch Mod
