cad:
- CAD/v0_1515_led_diffuser_assembly.f3d
- CAD/v0_1515_led_diffuser_assembly.step
description: Snap in 1515 Led mount for WS2812B
images:
- IMG/colors.jpg
- IMG/led_strip.jpg
- IMG/wiring.jpg
- IMG/print_finish.gif
mod_version: 1
printer_compatibility:
- V0.2
title: 1515 LED Mount
