cad:
- CAD/sturdy_handles.step
- CAD/sturdy_handles.f3d
description: Modified v2.2 handles with no panel rest and with 4 anchor points
discord_username: jeoje
images:
- images/side_profile.png
- images/offset_profile.png
- images/photo.png
mod_version: 1
printer_compatibility:
- V2.4
title: Sturdy Handles
