cad:
- CAD/Stealth_Rapido_UHF.step
description: Stealthburner mod for Rapido UHF
discord_username: bythorsthunder
images:
- IMAGES/Stealth_UHF_Side.jpg
- IMAGES/Stealth_UHF.jpg
mod_version: 1
printer_compatibility:
- V2.4
- VSW
- Trident
title: Stealthburner Rapido UHF
