cad: []
description: V2.4 Duet 3 6HC Din Bracket
discord_username: DorjeDorf
images:
- Example_print-courtesy_of_medicusdkfz.jpg
mod_version: 1
printer_compatibility:
- V2.4
title: Duet 3 6HC Din Bracket
