cad: []
description: Mounting bracket for a Logitech C920 on the tophat
discord_username: Koios
images:
- Images/Cable_Routing.jpg
- Images/Mount.jpg
- Images/From_Above.jpg
mod_version: 1
printer_compatibility:
- V0
title: V0 C920 Tophat Mount
