cad: []
description: Mounting bracket for a Logitech C920 on the tophat
images:
- Images/Cable_Routing.jpg
- Images/Mount.jpg
- Images/From_Above.jpg
mod_version: 1
printer_compatibility:
- V0.2
title: V0 C920 Tophat Mount
