cad:
- CAD/Mini_Afterburner_Strain_Relief.f3d
description: A replacement strain relief for the Mini Afterburner toolhead
discord_username: Andre
images:
- Images/CAD_1.png
- Images/CAD_3.png
- Images/CAD_2.png
mod_version: 1
printer_compatibility:
- V0
title: Mini Afterburner Strain Relief
