cad: []
description: Added a dual color file for the Voron Display Front housing
discord_username: hartk1213
images:
- Images/display.jpg
mod_version: 1
printer_compatibility:
- V0
title: Voron0 display dualcolor
