cad:
- STEP/SkirtPower.step
description: Skirt-mounted rocker switch for easy access for Voron 2.4
images:
- images/SkirtPower.png
- images/SkirtPower-photo.png
mod_version: 1
printer_compatibility:
- V2.4
title: Side Skirt Power Switch
