cad: []
description: New extended legs to raise the printer up a tiny bit more
discord_username: hartk1213
images:
- Images/1.jpg
mod_version: 1
printer_compatibility:
- V0
title: Voron0 ExtendedLegs
