cad: []
description: Created a new skirt design that uses 50mm extrusions as legs and it has
  a c14 power inlet hole on the bottom
images:
- Images/1.png
mod_version: 1
printer_compatibility:
- V0
title: Voron0 ExtrusionSkirt
