cad:
- CAD/Bed_Support_Alignment_Tools_v15.f3d
description: The bed support alignment tools will assist in helping align the "bed
  support extrusions" to the frame. When the alignment tools are placed in all four
  corners of the Voron Printer's frame the "bed support extrusions" will butt up against
  these tools so that you can screw the "bed support extrusions" down to the printer's
  frame in the correct position.
images:
- images/Bed_Suport_Alignment_Tools_each_pointed_out.jpg
- images/Bed_Support_Alignment_Tools.jpg
mod_version: 1
printer_compatibility:
- V2.4
title: Bed Support Extrusions Alignment Tools
