cad: []
description: Bracket for Raspberry pi zero.
discord_username: oxno
images:
- rbp_bracket_front.png
- rbp_bracket_back.png
mod_version: 1
printer_compatibility:
- V1.8
- V2.4
title: RBP Zero Bracket
