cad: []
description: SW plate for enclosure
discord_username: sloscotty
images:
- Images/printed_pieces.jpg
- Images/SW_plate_rendered.jpg
- Images/assembled1.jpg
- Images/SW_backwall_plate.jpg
- Images/base_inserts.jpg
mod_version: 1
printer_compatibility:
- VSW
title: Switchwire Wall Plate
