cad: []
description: Changes the gearing for the AB drives to improve both resolution and
  torque, with a strenthened frame.
images:
- ABcloseup.jpg
- reduction_overview.jpg
- reduction.png
mod_version: 1
printer_compatibility:
- V2.4
title: Precision AB Drive
