cad: []
description: A simple DIN rail mount for the 4 channel relay board for Raspberry Pi
discord_username: xbst_
images: []
mod_version: 1
printer_compatibility:
- V1.8
- V2.4
title: DIN Mount Pi 4x Relay Board
