cad:
- CAD/led_mount_clippable.step
description: LED Case light for the V0 that clips into the extrusions
discord_username: joposter
images:
- images/slicer_brim.jpg
- images/printer_installed.jpg
- images/cob_led.jpg
mod_version: 1
printer_compatibility:
- V0
title: V0 Clippable LED Caselight
