cad: []
description: A printed cover for v0 electronics. Requires larger printer to print.
discord_username: xbst_
images:
- example.jpg
mod_version: 1
printer_compatibility:
- V0
title: V0 Electronics Cover
