---
title: "FHeilmann's awesome mod"
description: "This mod does awesome things with awesome printers!"
printer_compatibility:
  - V1.8
  - VT
  - V2.4r2
images:
  - images/huvud_chain_mount.png
  - images/huvud_mount_install1.png
  - images/huvud_mount_install2.png
cad:
  - STEP/huvud_chain_mount_2_hole.step
  - STEP/huvud_chain_mount_3_hole.step
discord_username: haribrother
mod_version: 2
