cad:
- Front_Door_Mod.f3d
description: Voron 2.4 door hinges for 3mm panel, 180 deg opening and m3 screw as
  shaft
discord_username: quattroerik
images:
- Assembly.png
- door_hinge_new.png
mod_version: 1
printer_compatibility:
- V2.4
- Trident
title: V2.4 Door Hinge M3 3mm 180deg
