cad:
- CAD/HorseshoeSpoolHolder_v10.f3d
- CAD/HorseshoeSpoolHolder_v10.step
description: Horseshoe Spool Holder - mounts internally for Trident, or externally
  for V0, V1, or V2 printers.
images:
- ES.png
- PB.png
- TIS.png
- TI.jpg
mod_version: 1
printer_compatibility:
- V0.2
- V1.8
- V2.4
- VT
title: HorseshoeSpoolHolder
