cad:
- CAD/Mid_Panel_with_cablemanagement.step
- CAD/Mid_Panel.step
description: Panel for SKR1.4/1.4 or SKR E3 mini mount
images:
- Images/2.jpg
- Images/1.jpg
mod_version: 1
printer_compatibility:
- V0.2
title: Mid Panel
