cad:
- CAD/Dragon_AB_4020_1.step
- CAD/Rapido_AB_4020_2.step
- CAD/RevoVoron_AB_4020.step
description: Improved Dragon and Rapido toolhead for stock Afterburner with 4020 fan
images: []
mod_version: 1
printer_compatibility:
- V1.8
- V2.4
- VSW
- Trident
title: AB-BN for Stock Afterburner (4020)
