cad:
- cad/300LeadScrewMount.step
- cad/250LeadScrewBlock.step
- cad/ZMotorMount.step
description: Add MGN12H linear rails for Z axis motion
discord_username: piet206
images:
- isoview1.png
mod_version: 1
printer_compatibility:
- V1.8
title: V1.8 Z Rails Mod
