cad:
- thermistor_holder_zero.step
description: Extended thermistor holder for Voron Zero
images:
- thermistor_holder_comparison.png
- installed.png
mod_version: 1
printer_compatibility:
- V0
- VSW
- Trident
title: Thermistor holder zero
