cad: []
description: Voron Exhaust Filter Inserts for Activated Coal + Hepa
images:
- Images/VEFACH.png
- Images/4.jpg
- Images/5.jpg
- Images/CAD4.png
- Images/6.jpg
- Images/2.jpg
- Images/Trident_V2.png
- Images/CAD1.png
- Images/3.jpg
- Images/1.jpg
- Images/CAD3.png
- Images/CAD2.png
mod_version: 1
printer_compatibility:
- V2.4
- Trident
title: VEFACH
