cad:
- CAD/LoudOwl_v16.f3d
- CAD/LoudOwl_v16.step
- CAD/LoudOwl_for_split_ABBN_untested.step
description: Alternative dual 5015 part cooling fan toolhead for Afterburner
images:
- Visual/Supp_removal.jpg
- Visual/LoudOWL.jpg
- Visual/Wiring.jpg
- Visual/comparison.jpg
- Visual/Fans_in_place.jpg
- Visual/LoudOwl_2.jpg
- Visual/Using_cut_tool_3.jpg
- Visual/Using_cut_tool_2.jpg
- Visual/Using_cut_tool_1.jpg
mod_version: 1
printer_compatibility:
- V1.8
- V2.4
- VSW
title: LoudOwl aka Stabby
