cad:
- CAD/Handle_Mini_Front.step
- CAD/Door Frame.step
- CAD/Door_Latch_x2.step
description: Door in a frame
discord_username: JNP
images:
- Images/2.jpg
- Images/1.jpg
mod_version: 1
printer_compatibility:
- V0
title: Front Door
