cad:
- CAD/Drawer_Version_C.step
- CAD/Drawer_Version_B.step
- CAD/Drawer_Version_A.step
description: Drawer in four different versions
discord_username: JNP
images:
- Images/4.jpg
- Images/2.jpg
- Images/3.jpg
- Images/1.jpg
mod_version: 1
printer_compatibility:
- V0
title: Drawer
