cad:
- CAD/Bowden_Guide.step
description: Bowden tube guide and CANBUS wire support
images:
- IMAGES/Tube1.jpg
- IMAGES/chirpy.jpg
- IMAGES/Tube_Guide.png
- IMAGES/Short.jpg
- IMAGES/Dokuu.jpg
- IMAGES/chirpy2.jpg
mod_version: 1
printer_compatibility:
- V1.8
- V2.4
- VT
title: Bowden Tube Guide
