cad: []
description: relay-mount for 2x 2 channel relay modules.
discord_username: 42bios
images:
- relay_mount_printed.jpeg
- relay_mount2.png
- relay_mount1.png
mod_version: 1
printer_compatibility:
- V2.4
title: relay mount
