cad: []
description: A set of 2020-mounted cable guards to organize and dress the wiring on
  your build
images:
- Images/edge-clamp.png
- Images/combination.png
- Images/annotated.jpg
- Images/cable-mount.png
- Images/dressed.jpg
- Images/detail.jpg
mod_version: 1
printer_compatibility:
- V2.4
title: Voron 2.4 cable clamps
