cad:
- CAD/v0_direct_drive.step
description: A direct drive mod for the V0 using the Annex Sherpa Mini extruder
images: []
mod_version: 1
printer_compatibility:
- V0
title: V0 Sherpa Mini Direct Drive Mod
