cad:
- STEP/Guide-2-hole-Igus.step
- STEP/Guide-3-hole.step
- STEP/Key.step
description: Umbilical guide that goes on the chain anchor
discord_username: top_gun_de
images:
- Images/Umbilical-side.jpg
- Images/Umbilical-guide.jpg
- Images/Umbilical-rear.jpg
- Images/Umbilical-total.jpg
mod_version: 1
printer_compatibility:
- V2.4
title: mount_for_umbilical
