cad: []
description: Voron V0 SSR Mount for the bottom
discord_username: DaGlo
images:
- Voron_V0_SSR_Mount_v5_Back.png
- Voron_V0_SSR_Mount_Install_Step_1.jpg
- Voron_V0_SSR_Mount_Install_Step_2.jpg
- Voron_V0_SSR_Mount_Install_Step_3.jpg
- Voron_V0_SSR_Mount_v5_Front.png
mod_version: 1
printer_compatibility:
- V0
title: Voron V0 SSR Mount
