cad:
- Hinges v2.4 Mod.f3d
description: Simple mod of print in place door hinges, which uses m3 screws as shafts.
images:
- Door Hinges mod with M3 35mm.png
mod_version: 1
printer_compatibility:
- V2.4
title: Door hinges with M3 screws shafts
