cad: []
description: Mod to mount a M4 extruder to a Voron 0 where pocketwatch extruder mounts
discord_username: xbst_
images:
- example.jpg
mod_version: 1
printer_compatibility:
- V0
title: Mobius 4 (M4) V0 Mod
