cad:
- Monster8_DIN_clip.step
description: DIN mount for Makerbase Monster8 V1/V2 controller
discord_username: clee
images:
- slicer.png
- example.jpg
mod_version: 1
printer_compatibility:
- V2.4
- Trident
title: Monster8 DIN Rail Mounts
