cad: []
description: A mount for LED strips and Picam for the V0.1
discord_username: ademuri
images:
- camera_mount_detail.jpg
- printer_with_rails.jpg
- camera_view.png
mod_version: 1
printer_compatibility:
- V0
title: Lights, Camera, Voron
