cad: []
description: DIN (rotated) and legacy adapters for boards like SKR mini E3.
discord_username: hijax_pl_
images: []
mod_version: 1
printer_compatibility:
- V2.4
title: Controler Board adapters
