name: VoronUsers PR CI
run-name: "#${{github.event.number}} - ${{github.event.pull_request.title}}"
on:
  pull_request:
    types: [opened, reopened, synchronize]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
permissions:
  pull-requests: write
jobs:
  check_whitespace:
    uses: VoronDesign/.github/.github/workflows/check-whitespace-cache.yml.yml@main
    with:
      branch: ${{ github.ref }}
      cache-key: file-cache-${{github.sha}}
      cache-directory: pr-files
      parent-job-name: ${{ github.job }}
  setup_python:
    needs: [check_whitespace]
    if: ${{ needs.check_whitespace.outputs.stl == 'true' }}
    uses: VoronDesign/.github/.github/workflows/prepare-environment.yml@main
    with:
      apt-packages: "admesh, libadmesh-dev"
      pip-packages: "admesh imagekitio git+https://github.com/ChristophSchranz/Tweaker-3.git"
      python-cache-key: voronusers-python-cache
  check_stl_corruption:
    needs: [setup_python]
    if: ${{ needs.checkout_check_whitespace.outputs.stl == 'true' }}
    uses: VoronDesign/.github/.github/workflows/check-stl-corruption.yml@main
    with:
      cache-key: file-cache-${{github.sha}}
      cache-directory: pr-files
      python-cache-key: voronusers-python-cache
      parent-job-name: ${{ github.job }}
  check_stl_rotation:
    needs: [setup_python]
    if: ${{ needs.checkout_check_whitespace.outputs.stl == 'true' }}
    uses: VoronDesign/.github/.github/workflows/check-stl-rotation.yml@main
    with:
      imagekit-url-endpoint: https://ik.imagekit.io/vorondesign
      cache-key: file-cache-${{github.sha}}
      cache-directory: pr-files
      python-cache-key: voronusers-python-cache
      parent-job-name: ${{ github.job }}
  check_metadata:
    name: Check metadata files
    needs: [check_whitespace]
    if: ${{ needs.checkout_check_whitespace.outputs.yaml == 'true' }}
    uses: VoronDesign/.github/.github/workflows/check-metadata-files.yml@main
    with:
      cache-key: file-cache-${{github.sha}}
      cache-directory: pr-files
      parent-job-name: ${{ github.job }}
  preview_readme:
    name: Preview README.md
    needs: [check_metadata]
    uses: VoronDesign/.github/.github/workflows/preview-readme.yml@main
    with:
      subdirectory: printer_mods
      cache-key: file-cache-${{github.sha}}
      cache-directory: pr-files
  prepare_pr_comment:
    name: Store PR comment parameters
    # Dispatching allows us to run in the context of our repo, with sufficient credentials to do PR comments/set labels. We pass the
    # information that the dispatched workflow can't deduce on its own via the client payload parameter
    needs: [check_whitespace, check_stl_corruption, check_stl_rotation, check_metadata, preview_readme]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Save PR number
        run: |
          mkdir -p ${{ runner.temp }}/pr
          echo -n ${{ github.event.number }} > ${{ runner.temp }}/pr/pr_number
          echo -n ${{ github.run_id }} > ${{ runner.temp }}/pr/action_run_id
          echo -n ${{ needs.check_stl_rotation.outputs.rotation_suggested }} > ${{ runner.temp }}/pr/rotation_suggested
      - uses: actions/upload-artifact@65d862660abb392b8c4a3d1195a2108db131dd05
        with:
          name: pr
          path: ${{ runner.temp }}/pr
