cad:
- CAD/V01_skirt_button.step
description: Buttons for V0.1 spec skirts
discord_username: Tircown
images:
- Images/picture1.jpg
- Images/picture0.jpg
- Images/cad_split.jpg
mod_version: 1
printer_compatibility:
- V0
title: V0.1 Skirt buttons
